ManagementShop/Controllers/WorkSpaceController.cs
using DonaMenina.Context;
using DonaMenina.Entities;
using DonaMenina.Filters;
using DonaMenina.Helper;
using DonaMenina.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Query.Internal;
using Newtonsoft.Json;
using System.Globalization;

namespace DonaMenina.Controllers
{
    [PageForLoginUser]
    public class WorkSpaceController : Controller
    {
        private readonly DataBaseContext _dbContext;
        private readonly IUserSession _session;
        private readonly ISaleSession _saleSession;

        public WorkSpaceController(DataBaseContext context, IUserSession session, ISaleSession saleSession)
        {
            _dbContext = context;
            _session = session;
            _saleSession = saleSession;
        }

        [HttpPost]
        public IActionResult InsertWorker(Worker worker)
        {
            if (ModelState.IsValid)
            {
                _dbContext.Workers.Add(worker);
                _dbContext.SaveChanges();

                return RedirectToAction(nameof(Sucess), new {sucess = "Inserir Funcionario"});
            }
            return RedirectToAction(nameof(ManageWorker));
        }

        [HttpPost]
        public IActionResult EditWorker(Worker worker)
        {
            var workerDB = _dbContext.Workers.Find(worker.WorkerId);

            workerDB.Name = worker.Name;
            workerDB.Password = worker.Password;
            workerDB.IsActive = worker.IsActive;
            workerDB.IsAdm = worker.IsAdm;

            _dbContext.Workers.Update(workerDB);
            _dbContext.SaveChanges();

            return RedirectToAction(nameof(Sucess), new {sucess = "Editar Funcionário" });
        }

        public IActionResult EditWorker(int Id)
        {
            var worker = _dbContext.Workers.Find(Id);
            if (worker == null) return NotFound();
            return View(worker);
        }

        public IActionResult ManageWorker()
        {
            var workers = _dbContext.Workers.ToList();
            return View(workers);
        }

        public ActionResult ManageProducts()
        {
            var products = _dbContext.Products.ToList();
            return View(products);
        }
        public IActionResult Reports()
        {
            var mergeClass = _dbContext.MergeClasses
                .Include(mc => mc.Product)
                .Include(mc => mc.Sale)
                .Include(mc => mc.Worker)
                .ToList();

            return View(mergeClass);
        }

        [HttpPost]
        public IActionResult InsertProduct(Product product)
        {
            _dbContext.Products.Add(product);
            _dbContext.SaveChanges();
            return RedirectToAction(nameof(Sucess), new {sucess = "Inserir Produto" });
        }

        public ActionResult EditProducts(int id)
        {
            var product = _dbContext.Products.Find(id);
            if (product == null) return NotFound();
            return View(product);
        }

        [HttpPost]
        public ActionResult EditProduct(Product product)
        {
            var productDB = _dbContext.Products.Find(product.ProductId);

            productDB.ProductName = product.ProductName;
            productDB.Brand = product.Brand;
            productDB.Quantity = product.Quantity;
            productDB.Price = product.Price;
            

            _dbContext.Products.Update(productDB);
            _dbContext.SaveChanges();

            
            return RedirectToAction(nameof(Sucess), new {sucess = "Editar Produto" });
            
        }
        public ActionResult InsertProduct()
        {
            return View();
        }

        public IActionResult WorkSpace(string password)
        {
            var worker = _dbContext.Workers.FirstOrDefault(w => w.Password == password);
            WorkSpaceModel workSpaceModel = new WorkSpaceModel();
            workSpaceModel.Worker = worker;
            workSpaceModel.Products = _dbContext.Products.ToList();
            _session.BuildUserSession(workSpaceModel.Worker);
            workSpaceModel.ShoppingCart = new List<Product>();

            return View(workSpaceModel);
        }

        [HttpPost]
        public IActionResult ConfirmPurchase(ProductList products)
        {

            WorkSpaceModel workSpaceModel = new WorkSpaceModel();

            string[] arrayId = products.IdList.Split(" ");
            int[] intId = new int[arrayId.Length];

            for (int i = 0; i < arrayId.Length; i++)
            {
                intId[i] = int.Parse(arrayId[i]);
                workSpaceModel.IdProducts.Add(intId[i]);
                workSpaceModel.ShoppingCart.Add(_dbContext.Products.Find(intId[i]));
            }

            string[] arrayQuantity = products.QuantityList.Split(" ");
            int[] intQuantity = new int[arrayQuantity.Length];


            for (int i = 0; i < arrayQuantity.Length; i++)
            {
                intQuantity[i] = int.Parse(arrayQuantity[i]);
                workSpaceModel.QuantitySold.Add(intQuantity[i]);
                workSpaceModel.ShoppingCart[i].Quantity = intQuantity[i];
            }

            workSpaceModel.Worker = _session.GetWorkerSession();

            var lastIDSale = _dbContext.Sales.OrderByDescending(x => x.SaleId).Select(x => x.SaleId).FirstOrDefault();

            var nextIDSale = (lastIDSale != 0) ? lastIDSale + 1 : 1;

            _saleSession.BuildSaleSession(workSpaceModel);

            return View(workSpaceModel);
        }

        [HttpPost]
        public IActionResult SavePurchase(string discount, string paymentMethod, string totalSale)
        {
            var workSpace = _saleSession.GetSaleSession();

            if (string.IsNullOrEmpty(discount))
            {
                discount = "0";
            }
            workSpace.Sale.PriceDiscount = int.Parse(discount);
            workSpace.Sale.PaymentMethod = paymentMethod;
            workSpace.Sale.TotalSale = decimal.Parse(totalSale);
            workSpace.Sale.DataSale = DateTime.Now;

            _dbContext.Add(workSpace.Sale);
            _dbContext.SaveChanges();

            var lastIDSale = _dbContext.Sales.OrderByDescending(x => x.SaleId).Select(x => x.SaleId).FirstOrDefault();

            foreach (Product product in workSpace.ShoppingCart)
            {
                MergeClass mergeClass = new MergeClass();
                mergeClass.SaleId = lastIDSale;
                mergeClass.WorkerID = workSpace.Worker.WorkerId;
                mergeClass.ProductId = product.ProductId;
                mergeClass.QuantitySold = product.Quantity;

                Product productToUpdate = _dbContext.Products.Find(product.ProductId);
                productToUpdate.Quantity -= product.Quantity;

                _dbContext.Update(productToUpdate);
                _dbContext.Add(mergeClass);
            }

            _dbContext.SaveChanges();

            _saleSession.EndSaleSession();

            return RedirectToAction(nameof(Sucess), new {sucess = "Venda Realizada" });
        }

        public IActionResult Sucess(string sucess)
        {
            SucessModel sucessModel = new SucessModel(sucess);
            return View(sucessModel);
        }
    }
}

ManagementShop/Views/WorkSpace/ConfirmPurchase.cshtml
@model DonaMenina.Models.WorkSpaceModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

}
<head>
    <title>Confirmar Compra</title>
    <link rel="stylesheet" href="~/css/worksapce.css">
</head>
<body>

    <section class="work-area confirm">
        <div class="title">
            <h2>Carrinho de compras</h2>
        </div>


        <table id="product-table">
            <thead>
            <th>Código</th>
            <th>Nome</th>
            <th>Marca</th>
            <th>Tamanho</th>
            <th>Preço</th>
            <th>Quantidade</th>
            </thead>
            <tbody>
                @foreach (var product in Model.ShoppingCart)
                {
                    <tr>
                        <td class="product-id">@product.ProductId</td>
                        <td class="product-name">@product.ProductName</td>
                        <td class="product-brand">@product.Brand</td>
                        <td class="product-size">@product.Size</td>
                        <td class="product-price">@product.Price</td>
                        <td class="product-quantity">@product.Quantity</td>
                    </tr>
                }
            </tbody>
        </table>
        <form id="payment" method="post" asp-action="SavePurchase" asp-controller="WorkSpace">
            <label>Forma de pagamento: </label>
            <select name="paymentMethod" id="payment-method">
                <option value="Pix">Pix</option>
                <option value="Especie">Espécie</option>
                <option value="Debito">Débito</option>
                <option value="Credito">Crédito</option>
            </select>
            <br><br>
            <div>
                <label for="">Aplicar Desconto: <input type="number" id="discont" name="discount" placeholder="0" oninput="validateNumber(this)" pattern="[0-9]" min="0" max="100"> %</label>
            </div>
            <br>
            <div>
                <label id="price">Valor: </label> <br>
                <label id="total-value">Total a pagar: </label>
                <input readonly id="total-price" name="totalSale" hidden />
            </div>
            <br>
            <div class="buttons-sale">
                <a role="button" asp-action="Index" asp-controller="Home" class="button-a">Voltar</a>
                <button type="submit">Confirmar</button>
            </div>
        </form>
    </section>
    <div class="end-page">
    </div>
</body>

<script src="~/js/confirmpurchase.js"></script>

ManagementShop/Views/WorkSpace/EditProducts.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<head>
<link rel="stylesheet" href="~/css/ManageWorker.css" />
</head>

@model DonaMenina.Entities.Product

<body>
    <section>
        <div class="border-div">
            <h2 align="center">Editar Produto</h2>
            <form method="post" class="form-product" asp-action="EditProduct">
                <div>
                    <label for="">Código: @Model.ProductId</label>
                    <input name="ProductId" value="@Model.ProductId" hidden />
                </div>
                <div>
                    <input type="text" name="ProductName" placeholder="Nome do Produto" value="@Model.ProductName">
                    <input type="text" name="Brand" placeholder="Marca do Produto" value="@Model.Brand">
                </div>
                <div>
                    <label for="size">Tamanho: </label>
                    <select name="Size" id="size" readonly>
                        <option value="@Model.Size">@Model.Size</option>
                    </select>
                    <label for="price">Preço:</label>
                    <input type="text" name="Price" id="price" value="@Model.Price" readonly>
                </div>
                <div>
                    <label for="quantity">Quantidade em estoque: </label>
                    <input type="number" name="Quantity" id="quantity" value="@Model.Quantity" required>
                </div>
                <div class="buttons-align">
                    <a role="button" asp-action="ManageProducts" asp-controller="WorkSpace" class="button-a">Voltar</a>
                    <button type="submit">Atualizar</button>
                </div>
                
            </form>
        </div>
    </section>
    <div class="end-page">
    </div>
</body>

ManagementShop/Views/WorkSpace/EditWorker.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model DonaMenina.Entities.Worker

<head>
    <link rel="stylesheet" href="~/css/ManageWorker.css" />
</head>

<body>
    <section>
        <div class="border-div">
            <h1>Editar Funcionário</h1>
            <form method="post" asp-action="EditWorker" class="worker-form">
                <div>
                    <label>Id: </label> <input type="text" value="@Model.WorkerId" name="WorkerId" readonly />
                </div>
                <div>
                    <input type="text" value="@Model.Name" name="Name" required>
                </div>
                <div>
                    <input type="password" value="@Model.Password" name="Password" required>
                </div>
                <div>
                    <label for="">Funcionário Ativo: </label>
                    <input type="checkbox" name="IsActive" value="true" @(Model.IsActive ? "checked" : "")>
                </div>
                <div>
                    <label for="">Permissão de Gerente: </label>
                    <input type="checkbox" name="IsAdm" value="true" @(Model.IsAdm ? "checked" : "")>
                </div>
                <div class="buttons-align">
                    <a role="button" asp-action="ManageWorker" asp-controller="WorkSpace" class="button-a">Cancelar</a>
                    <button type="submit">Atualizar</button>
                </div>
            </form>
        </div>
    </section>
    <div class="end-page">
    </div>
    <script src="~/js/site.js"></script>
</body>

ManagementShop/Views/WorkSpace/InsertProduct.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<head>
    <link rel="stylesheet" href="~/css/ManageWorker.css" />
</head>
@model DonaMenina.Entities.Product
<body>
    <section>
        <div class="border-div">
            <h2 align="center">Cadastrar Produtos</h2>
            <form method="post" class="form-product" asp-action="InsertProduct">
                <div>
                    <label for="">Código: </label>
                </div>
                <div>
                    <input type="text" name="ProductName" placeholder="Nome do Produto" required>
                    <input type="text" name="Brand" placeholder="Marca do Produto" required>
                </div>
                <div>
                    <label for="size">Tamanho: </label>
                    <select name="Size" id="size">
                        <option value="Unico">Único</option>
                        <option value="PP">PP</option>
                        <option value="P">P</option>
                        <option value="M">M</option>
                        <option value="G">G</option>
                        <option value="GG">GG</option>
                    </select>
                    <label for="price">Preço:</label>
                    <input type="text" name="Price" id="price" oninput="formatValue(this)" placeholder="0,00" required>
                </div>
                <div>
                    <label for="quantity">Quantidade em estoque: </label>
                    <input type="number" name="Quantity" id="quantity" required>
                </div>
                <div class="buttons-align">
                    <a role="button" asp-action="ManageProducts" asp-controller="WorkSpace" class="button-a">Voltar</a>
                    <button type="submit">Cadastrar</button>
                </div>
            </form>
        </div>
    </section>
    <div class="end-page">
    </div>
    <script src="~/js/site.js"></script>
</body>

ManagementShop/Views/WorkSpace/ManageProducts.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<head>
    <script src="~/js/site.js"></script>
    <link rel="stylesheet" href="~/css/ManageWorker.css" />
</head>

@model IEnumerable<DonaMenina.Entities.Product>

<body>
    <section>
        <div class="border-div">
            <div>
                <h2 align="center">Gerenciar Produtos</h2>
            </div>
            <div>
                <button onclick="window.location.href='@Url.Action("InsertProduct","WorkSpace")'">Cadastrar novo Produto</button>
            </div>
            <div>
                <table class="table-container" id="table-products">
                    <thead>
                    <th>Codigo</th>
                    <th>Nome</th>
                    <th>Marca</th>
                    <th>Tamanho</th>
                    <th>Preço</th>
                    <th>Quantidade</th>
                    <th class="th-null"></th>
                    </thead>
                    <tbody>
                        @if (Model != null && Model.Count() != 0)
                        {
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(model => item.ProductId)</td>
                                    <td>@Html.DisplayFor(model => item.ProductName)</td>
                                    <td>@Html.DisplayFor(model => item.Brand)</td>
                                    <td>@Html.DisplayFor(model => item.Size)</td>
                                    <td>@Html.DisplayFor(model => item.Price)</td>
                                    <td>@Html.DisplayFor(model => item.Quantity)</td>
                                    <td> <a role="button" asp-action="EditProducts" asp-route-id="@item.ProductId" class="button-a">Editar</a> </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
            <br /><br />
            <a role="button" asp-action="Index" asp-controller="Home" class="button-a">Voltar</a>
        </div>
    </section>
    <div class="end-page">
    </div>
</body>

ManagementShop/Views/WorkSpace/ManageWorker.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model IEnumerable<DonaMenina.Entities.Worker>

<head>
    <script src="~/js/site.js"></script>
    <link rel="stylesheet" href="~/css/ManageWorker.css" />
</head>
<body>
    <section>
        <div class="border-div">
            <h1>Cadastrar Funcionário</h1>
            <form method="post" asp-action="InsertWorker" id="insert-worker" class="worker-form">
                <div>
                    <input type="text" name="Name" placeholder="Nome do Funcionário" required>
                </div>
                <div>
                    <input type="password" name="Password" placeholder="Criar Senha de acesso" required>
                </div>
                <div>
                    <label for="">Funcionário Ativo: </label> <input type="checkbox" value="true" name="IsActive">
                </div>
                <div>
                    <label for="">Acesso Gerente: </label> <input type="checkbox" value="true" name="IsAdm">
                </div>
                <div class="buttons-align">
                    <a role="button" asp-action="Index" asp-controller="Home" class="button-a">Voltar</a>
                    <button type="submit">Cadastrar</button>
                </div>

            </form>
        </div>

        <div class="border-div">
            <h1>Lista de funcionários</h1>
            <table>
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Nome</th>
                        <th>Ativo</th>
                        <th>Gerente</th>
                        <th class="th-null"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach(var item in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(model => item.WorkerId)</td>
                            <td>@Html.DisplayFor(model => item.Name)</td>
                            <td>@Html.DisplayFor(model => item.IsActive)</td>
                            <td>@Html.DisplayFor(model => item.IsAdm)</td>
                            <td> <a role="button" asp-action="EditWorker" asp-route-id="@item.WorkerId" class="button-a">Editar</a> </td>
                        </tr>
                    }
                </tbody>

            </table>
        </div>
    </section>
    <div class="end-page">
    </div>
</body>

ManagementShop/Views/WorkSpace/Reports.cshtml
@model IEnumerable<DonaMenina.Entities.MergeClass>;
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<head>
    <link rel="stylesheet" href="~/css/ManageWorker.css" />
</head>

<body>

    <section class="reports">
        <div class="border-div">
            <h1 align="center">Relatórios de venda</h1>

            <div class="search-area">
            </div>
            <div class="table-container">
                <table class="table" id="table-products">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Vendedor</th>
                            <th>Produto Vendido</th>
                            <th>Quantidade Vendida</th>
                            <th>Forma de Pagamento</th>
                            <th>Preço Unitário</th>

                            <th>Data</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null)
                        {
                            @foreach (var sale in Model)
                            {
                                <tr>
                                    <td class="product-id">@sale.SaleId</td>
                                    <td class="product-name">@sale.Worker.Name</td>
                                    <td class="product-brand">@sale.Product.ProductName</td>
                                    <td class="product-size">@sale.QuantitySold</td>
                                    <td class="product-size">@sale.Sale.PaymentMethod</td>
                                    <td class="product-price">@sale.Product.Price</td>
                                    <td class="product-quantity">@sale.Sale.DataSale</td>
                                    <td class="product-quantity">@sale.Sale.TotalSale</td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
            <br /><br /><br />
            <a role="button" asp-action="Index" asp-controller="Home" class="button-a">Voltar</a>
        </div>
    </section>



    <div class="end-page">
    </div>
</body>

ManagementShop/Views/WorkSpace/Sucess.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<head>
    <title>Dona Menina</title>
    <link rel="stylesheet" href="~/css/worksapce.css">
</head>

@model DonaMenina.Models.SucessModel

<body>
    <section class="home">
        <div class="border-div ">
            <div class="buttons-align center-div">
                @if (Model.Sucess == "Editar Produto")
                {
                    <h2 align="center">Produto Atualizado com sucesso!</h2>

                    <a role="button" asp-action="ManageProducts" asp-controller="WorkSpace" class="button-a">Voltar</a>
                }
                @if (Model.Sucess == "Editar Funcionário")
                {
                    <h2 align="center">Funcionário Atualizado com sucesso!</h2>

                    <a role="button" asp-action="ManageWorker" asp-controller="WorkSpace" class="button-a">Voltar</a>
                }
                @if (Model.Sucess == "Inserir Produto")
                {
                    <h2 align="center">Produto Inserido com sucesso!</h2>

                    <a role="button" asp-action="ManageProducts" asp-controller="WorkSpace" class="button-a">Voltar</a>
                }
                @if (Model.Sucess == "Inserir Funcionario")
                {
                    <h2 align="center">Funcionário Cadastrado com Sucesso!</h2>

                    <a role="button" asp-action="ManageWorker" asp-controller="WorkSpace" class="button-a">Voltar</a>
                }
                @if (Model.Sucess == "Venda Realizada")
                {
                    <h2 align="center">Venda Realizada com sucesso!</h2>
                    <a role="button" asp-action="Index" asp-controller="Home" class="button-a">Voltar</a>
                }
            </div>
        </div>
    </section>
    <div class="end-page">
    </div>
</body>

ManagementShop/Views/WorkSpace/WorkSpace.cshtml
@model DonaMenina.Models.WorkSpaceModel;
@using Newtonsoft.Json

@{
    ViewData["Title"] = "Bem vindo";
}

<head>
    <script src="~/js/site.js"></script>
    <link rel="stylesheet" href="~/css/worksapce.css" />

</head>

<body>
    <div class="buttons-sale">
    <h1>Seção: @Html.DisplayFor(x => x.Worker.Name)</h1>
    <a role="button" asp-controller="Home" asp-action="Exit" class="button-a">Encerrar Seção</a>
    </div>
    <br />
    <br />
    <section>
        <div class="work-area form">
            <div class="table-container height-table">
                <table class="table" id="table-products">
                    <thead>
                        <tr>
                            <th>Código</th>
                            <th>Nome</th>
                            <th>Marca</th>
                            <th>Tamanho</th>
                            <th>Valor</th>
                            <th>QTD</th>
                            <th class="th-null"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var product in Model.Products)
                        {
                            <tr>
                                <td class="product-id">@product.ProductId</td>
                                <td class="product-name">@product.ProductName</td>
                                <td class="product-brand">@product.Brand</td>
                                <td class="product-size">@product.Size</td>
                                <td class="product-price">@product.Price</td>
                                <td class="product-quantity">@product.Quantity</td>
                                <td> <a href="#" onclick="AddProduct()" class="button-table" id="add-product" role="button" data-id="@product.ProductId" style="cursor: pointer">+</a></td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>

            <h2>Carrinho de Compras</h2>
            <form id="shopping-cart-form" method="post" asp-action="ConfirmPurchase" asp-controller="WorkSpace">
                <div class="table-container height-table">
                    <table id="table-shopping-cart">
                        <thead>
                            <tr>
                                <th>Código</th>
                                <th>Nome</th>
                                <th>Marca</th>
                                <th>Tamanho</th>
                                <th>Valor</th>
                                <th>QTD</th>
                                <th class="th-null"></th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
                <input type="text" id="id-list" class="id-list" name="IdList" hidden/>
                <input type="text" id="quantity-list" class="quantity-list" name="QuantityList" hidden/>

                <div class="buttons-sale">
                    <a role="button" class="button-a" asp-action="Index" asp-controller="Home">Limpar carrinho</a>
                    <button type="submit" class="adm-button-style" id="confirm-purchase">Confirmar Compra</button>
                </div>
            </form>
        </div>

        @{
            if (Model.Worker.IsAdm)
            {
                <form class="adm-area">
                    <div class="adm-button-style">
                        <button onclick="window.location.href='@Url.Action("ManageWorker","WorkSpace")'" type="button">Gerenciar Funcionários</button>
                    </div>
                    <div class="adm-button-style">
                        <button onclick="window.location.href='@Url.Action("ManageProducts","WorkSpace")'" type="button">Gerenciar Mercadorias</button>
                    </div>
                    <div class="adm-button-style">
                        <button onclick="window.location.href='@Url.Action("Reports","WorkSpace")'" type="button">Relatório de vendas</button>
                    </div>
                </form>
            }
        }
        
    </section>
    <div class="end-page">
    </div>
</body>